application: nobena-stran
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets
  
- url: /
  script: main.php

- url: /confirmation
  script: confirmation.php
  
  